name: Build

# yamllint disable-line rule:truthy
on:
  check_run:
    types:
    - rerequested
    - requested_action
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        # TODO: update to 1.15.x once 1.15.4 released
        go-version: 1.14.x

    - name: Build
      run: |
        CGO_ENABLED=0 make arhat-none.linux.all
        CGO_ENABLED=0 make arhat-docker.linux.all
        CGO_ENABLED=1 make arhat-libpod.linux.all

    - name: Package
      run: |
        make package.arhat-none.linux.all
        make package.arhat-docker.linux.all
        make package.arhat-libpod.linux.all

    - name: Hash
      run: |
        cd build
        sha256sum arhat-*.linux* > sha256.linux.txt
        sha512sum arhat-*.linux* > sha512.linux.txt
        md5sum arhat-*.linux* > md5.linux.txt
        cd -

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-on-linux
        path: build

  build-on-darwin:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        # TODO: update to 1.15.x once 1.15.4 released
        go-version: 1.14.x

    - name: Build
      run: |
        CGO_ENABLED=1 make arhat-none.darwin.all
        CGO_ENABLED=1 make arhat-docker.darwin.all

    - name: Package
      run: |
        make package.arhat-none.darwin.all
        make package.arhat-docker.darwin.all

    - name: Install md5sum
      run: |
        brew install md5sha1sum

    - name: Hash
      run: |
        cd build
        shasum -a 256 arhat-*.darwin* > sha256.darwin.txt
        shasum -a 512 arhat-*.darwin* > sha512.darwin.txt
        md5sum arhat-*.darwin* > md5.darwin.txt
        cd -

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-on-darwin
        path: build

  build-on-windows:
    runs-on: windows-latest
    shell: bash
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        # TODO: update to 1.15.x once 1.15.4 released
        go-version: 1.14.x

    - name: Build
      run: |
        CGO_ENABLED=0 make arhat-none.windows.all
        CGO_ENABLED=0 make arhat-docker.windows.all

    - name: Package
      run: |
        make package.arhat-none.windows.all
        make package.arhat-docker.windows.all

    - name: Hash
      run: |
        cd build
        sha256sum arhat-*.windows* > sha256.windows.txt
        sha512sum arhat-*.windows* > sha512.windows.txt
        md5sum arhat-*.windows* > md5.windows.txt
        cd -

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-on-windows
        path: build

  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs:
    - build-on-linux
    - build-on-windows
    - build-on-darwin

    runs-on: ubuntu-latest
    steps:
    - name: Download linux builds
      uses: actions/download-artifact@v2
      with:
        name: build-on-linux
        path: build

    - name: Download windows builds
      uses: actions/download-artifact@v2
      with:
        name: build-on-windows
        path: build

    - name: Download darwin builds
      uses: actions/download-artifact@v2
      with:
        name: build-on-darwin
        path: build
    
    - name: Extract tag name
      id: extract_tag
      run: |
        echo "::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: false
        body: |
          # Release Notes

          ## Features

          - `arhat-none`
          - `arhat-docker`
          - `arhat-libpod`
            - Add foo support #issue-ref
            - Add bar support #issue-ref

          ## Bug fixes

          - `arhat-none`
          - `arhat-docker`
          - `arhat-libpod`
            - Fixed foo #issue-ref
            - Fixed bar #issue-ref #pr-ref

          ## Breaking Changes

          - `arhat-none`
          - `arhat-docker`
          - `arhat-libpod`
            - Foo ...
            - Bar ...

          ## Images

          - `arhat-none`
            - `docker.io/arhatdev/arhat-none:${{ steps.extract_tag.outputs.tag }}`
            - `ghcr.io/arhat-dev/arhat-none:${{ steps.extract_tag.outputs.tag }}`
          - `arhat-docker`
            - `docker.io/arhatdev/arhat-docker:${{ steps.extract_tag.outputs.tag }}`
            - `ghcr.io/arhat-dev/arhat-docker:${{ steps.extract_tag.outputs.tag }}`
          - `arhat-libpod`
            - `docker.io/arhatdev/arhat-libpod:${{ steps.extract_tag.outputs.tag }}`
            - `ghcr.io/arhat-dev/arhat-libpod:${{ steps.extract_tag.outputs.tag }}`

    #
    # checksums
    #
    - name: Create Checksum Files
      run: |
        files="sha256 sha512 md5"
        for f in ${files}; do
          printf "# Linux builds\n\n" > "build/${f}.txt"
          cat build/${f}.linux.txt >> "build/${f}.txt"

          printf "# Darwin builds\n\n" >> "build/${f}.txt"
          cat build/${f}.darwin.txt >> "build/${f}.txt"

          printf "# Windows builds\n\n" >> "build/${f}.txt"
          cat build/${f}.windows.txt >> "build/${f}.txt"
        done

    - name: Upload sha256
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: sha256.txt
        asset_path: build/sha256.txt
        asset_content_type: text/plain

    - name: Upload sha512
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: sha512.txt
        asset_path: build/sha512.txt
        asset_content_type: text/plain

    - name: Upload md5
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: md5.txt
        asset_path: build/md5.txt
        asset_content_type: text/plain

    - name: Upload arhat-none.darwin.amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.darwin.amd64
        asset_path: build/arhat-none.darwin.amd64
        asset_content_type: application/octet-stream

    # TODO: support darwin/arm64 build
    # - name: Upload arhat-none.darwin.arm64
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_name: arhat-none.darwin.arm64
    #     asset_path: build/arhat-none.darwin.arm64
    #     asset_content_type: application/octet-stream

    - name: Upload arhat-none.windows.x86
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.windows.x86.exe
        asset_path: build/arhat-none.windows.x86.exe
        asset_content_type: application/x-ms-dos-executable

    - name: Upload arhat-none.windows.amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.windows.amd64.exe
        asset_path: build/arhat-none.windows.amd64.exe
        asset_content_type: application/x-ms-dos-executable

    # TODO: support windows/arm
    # - name: Upload arhat-none.windows.armv7
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_name: arhat-none.windows.armv7.exe
    #     asset_path: build/arhat-none.windows.armv7.exe
    #     asset_content_type: application/x-ms-dos-executable

    - name: Upload arhat-none.linux.x86
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.x86
        asset_path: build/arhat-none.linux.x86
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.amd64
        asset_path: build/arhat-none.linux.amd64
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.armv5
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.armv5
        asset_path: build/arhat-none.linux.armv5
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.armv6
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.armv6
        asset_path: build/arhat-none.linux.armv6
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.armv7
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.armv7
        asset_path: build/arhat-none.linux.armv7
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.arm64
        asset_path: build/arhat-none.linux.arm64
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.ppc64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.ppc64
        asset_path: build/arhat-none.linux.ppc64
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.ppc64le
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.ppc64le
        asset_path: build/arhat-none.linux.ppc64le
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.s390x
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.s390x
        asset_path: build/arhat-none.linux.s390x
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.mips
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.mips
        asset_path: build/arhat-none.linux.mips
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.mipshf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.mipshf
        asset_path: build/arhat-none.linux.mipshf
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.mipsle
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.mipsle
        asset_path: build/arhat-none.linux.mipsle
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.mipslehf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.mipslehf
        asset_path: build/arhat-none.linux.mipslehf
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.mips64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.mips64
        asset_path: build/arhat-none.linux.mips64
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.mips64hf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.mips64hf
        asset_path: build/arhat-none.linux.mips64hf
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.mips64le
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.mips64le
        asset_path: build/arhat-none.linux.mips64le
        asset_content_type: application/octet-stream

    - name: Upload arhat-none.linux.mips64lehf
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.linux.mips64lehf
        asset_path: build/arhat-none.linux.mips64lehf
        asset_content_type: application/octet-stream

    #
    # packages
    #

    - name: Upload arhat-none-amd64.deb
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.amd64.deb
        asset_path: build/arhat-none.amd64.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload arhat-none-x86_64.rpm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.x86_64.rpm
        asset_path: build/arhat-none.x86_64.rpm
        asset_content_type: application/x-rpm

    - name: Upload arhat-none-armel.deb
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.armel.deb
        asset_path: build/arhat-none.armel.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload arhat-none-armhf.deb
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.armhf.deb
        asset_path: build/arhat-none.armhf.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload arhat-none-armhfp.rpm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.armhfp.rpm
        asset_path: build/arhat-none.armhfp.rpm
        asset_content_type: application/x-rpm

    - name: Upload arhat-none-arm64.deb
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.arm64.deb
        asset_path: build/arhat-none.arm64.deb
        asset_content_type: application/vnd.debian.binary-package

    - name: Upload arhat-none-aarch64.rpm
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_name: arhat-none.aarch64.rpm
        asset_path: build/arhat-none.aarch64.rpm
        asset_content_type: application/x-rpm

    # - name: Upload arhat-none-arm64.msi
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_name: arhat-none.arm64.msi
    #     asset_path: build/arhat-none.arm64.msi
    #     asset_content_type: application/x-msdownload

    # - name: Upload arhat-none-amd64.msi
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_name: arhat-none.amd64.msi
    #     asset_path: build/arhat-none.amd64.msi
    #     asset_content_type: application/x-msdownload

    # - name: Upload arhat-none-arm64.pkg
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_name: arhat-none.arm64.pkg
    #     asset_path: build/arhat-none.arm64.pkg
    #     asset_content_type: application/octet-stream

    # - name: Upload arhat-none-amd64.pkg
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_name: arhat-none.amd64.pkg
    #     asset_path: build/arhat-none.amd64.pkg
    #     asset_content_type: application/octet-stream
